### ISSUE TITLE
JSON parse error embedding array of strings

### ISSUE THREAD

**Issue by RecuencoJones** [seznam/halson#9]
Cannot embed simple arrays of strings, JSON parse error is thrown.

e.g:

```
const halson = require("halson")

halson().addEmbed('product', [ '"foo"', '"bar"' ])
```

https://runkit.com/recuencojones/5bfbd0b446ad9c0012798d26

The problem comes from here: https://github.com/seznam/halson/blob/master/index.js#L5-L7

**Comment by jerrymf** [comment]
Hello,

Your usecase is incorrect, please follow formal specification https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1.2 .

> The reserved "_embedded" property is OPTIONAL

> It is an object whose property names are link relation types (as
   defined by [RFC5988]) and values are either a Resource Object or an
   array of Resource Objects.

> Embedded Resources MAY be a full, partial, or inconsistent version of
   the representation served from the target URI.
